### ISSUE TITLE
The labels is not colorful?

### ISSUE THREAD

**Issue by Echosanmao** [JDAI-CV/lapa-dataset#1]
Hi~
Thank you for sharing this wonderful work.
Today I am learning this LaPa datasets, but after I download it I find that the labels in the files is not colorful, so I just what to know is my download method wrong? 
Thanks !!

**Comment by lucia123** [comment]
Hi, thank you for following our work. The label maps are saved as gray images(0-10), and you can use the colormap that we provided to visualize them.

**Comment by lucia123** [comment]
> Hi~
> Thank you for sharing this wonderful work.
> Today I am learning this LaPa datasets, but after I download it I find that the labels in the files is not colorful, so I just what to know is my download method wrong?
> Thanks !!

Hi, thank you for following our work. The label maps are saved as gray images(0-10), and you can use the colormap that we provided to visualize them.
