### ISSUE TITLE
论文的链接失效

### ISSUE THREAD

**Issue by BlueWinters** [JDAI-CV/lapa-dataset#4]
无法打开PDF：`https://www.aaai.org/Papers/AAAI/2020GB/AAAI-LiuY.6557.pdf`

**Comment by TracelessLe** [comment]
> 无法打开PDF：`https://www.aaai.org/Papers/AAAI/2020GB/AAAI-LiuY.6557.pdf`

@BlueWinters The PDF is attached as follows:
[A New Dataset and Boundary-Attention Semantic Segmentation for Face Parsing-liu2020.pdf](https://github.com/JDAI-CV/lapa-dataset/files/5249067/A.New.Dataset.and.Boundary-Attention.Semantic.Segmentation.for.Face.Parsing-liu2020.pdf)
