### ISSUE TITLE
The link to the paper is broken

### ISSUE THREAD

**Issue by Shreeyak** [JDAI-CV/lapa-dataset#5]
Even the link found by a google search is broken:
https://www.aaai.org/Papers/AAAI/2020GB/AAAI-LiuY.6557.pdf

**Comment by lucia123** [comment]
> Even the link found by a google search is broken:
> https://www.aaai.org/Papers/AAAI/2020GB/AAAI-LiuY.6557.pdf

https://aaai.org/ojs/index.php/AAAI/article/view/6832
